databases:
  - name: blog
    databaseName: blog_z6at
    user: blog_z6at_user
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: postgresql://blog_z6at_user:MPa9DD3QMb2JHVfzOjvuJMz8vn7jvGnG@dpg-cq0s5v6ehbks73egvlbg-a/blog_z6at
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default